{% set version = "1.0.4" %}

package:
  name: libusb-compat
  version: {{ version }}

source:
  url: http://downloads.sourceforge.net/libusb/libusb-{{ version }}.tar.bz2
  sha256: 6de182e93c946d432ed04362f0b93d889072438448dad20a21d4fcfa34cffa1d

build:
  number: 0
  run_exports:
    # This package is very unlikely to change in the near future as it is
    # legacy code
    - {{ pin_subpackage('libusb-compat') }}
  # For now, start with linux builds ony
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - libtool  # [unix]
    - pkg-config  # [unix]
    - make  # [unix]

test:
  commands:
    - test -f $PREFIX/include/usb.h
    - test -f $PREFIX/include/usbpp.h
    - test -f $PREFIX/bin/libusb-config
    - test -f $PREFIX/lib/libusb.so
    - test -f $PREFIX/lib/libusb-0.1.so.4

about:
  home: https://sourceforge.net/projects/libusb/files/libusb-0.1%20%28LEGACY%29/
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: (Legacy) A cross-platform library that gives apps easy access to USB devices

extra:
  recipe-maintainers:
    - hmaarrfk
